current_dir := ${CURDIR}
TARGET := arty_35
TOP := top
SOURCES := ${current_dir}/PWM.v
SOURCES += ${current_dir}/pulse_led.v

XDC := ${current_dir}/arty_35.xdc

include ${current_dir}/../../common/common.mk