current_dir := ${CURDIR}
proj_f_dir := ${current_dir}/../../../../projf-explore/hello/hello-arty/A
SUBPROJECT := A
BUILDDIR := ${current_dir}/../../../../hello-build

TOP := top
SOURCES := ${proj_f_dir}/top.sv

XDC := ${proj_f_dir}/arty.xdc


include ${current_dir}/../../../common.mk