current_dir := ${CURDIR}
proj_f_dir := ${current_dir}/../../../../third_party/projf-explore/hello/hello-arty/G

TOP := top
SOURCES := ${proj_f_dir}/top.sv
XDC := ${proj_f_dir}/arty.xdc

include ${current_dir}/../../../../common/common.mk
