current_dir := ${CURDIR}
TOP := top
SOURCES := ${current_dir}/baselitex_arty.v \
           ${current_dir}/../../third_party/vexriscv-verilog/VexRiscv_Linux.v

SDC := ${current_dir}/arty.sdc
XDC := ${current_dir}/arty.xdc

include ${current_dir}/../../common/common.mk
